pipeline:
    name: harness-buildpacks
    identifier: Harness_Buildpacks_Plugin_Build
    projectIdentifier: Plugins
    orgIdentifier: default
    tags: {}
    properties:
        ci:
            codebase:
                connectorRef: lukehertert_GitHub_Org
                repoName: harness-buildpacks
                build:
                    type: branch
                    spec:
                        branch: main
    stages:
        - stage:
              name: Build
              identifier: Build
              type: CI
              spec:
                  cloneCodebase: true
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: laptopk8s
                          namespace: default
                          automountServiceAccountToken: true
                          nodeSelector: {}
                          os: Linux
                  execution:
                      steps:
                          - step:
                                spec:
                                    connectorRef: account.Luke_Dockerhub
                                    image: plugins/docker
                                    privileged: true
                                    settings:
                                        dockerfile: Dockerfile
                                        pull_image: false
                                        daemon_off: false
                                        launch_debug: false
                                        squash: false
                                        bip: false
                                        tags: <+pipeline.sequenceId>
                                        username: ldhertert
                                        force_tag: false
                                        purge: false
                                        experimental: "true"
                                        repo: <+stage.variables.image>
                                        debug: false
                                        password: <+secrets.getValue("account.Luke_Dockerhub_Password")>
                                        insecure: false
                                        auto_tag: "true"
                                        compress: false
                                        dry_run: "true"
                                type: Plugin
                                name: Docker stuff
                                identifier: Docker_stuff
                          - parallel:
                                - step:
                                      type: BuildAndPushDockerRegistry
                                      name: Publish to DockerHub
                                      identifier: dockerhub
                                      spec:
                                          connectorRef: account.Luke_Dockerhub
                                          repo: ldhertert/<+stage.variables.image>
                                          tags:
                                              - <+codebase.branch>-<+codebase.commitSha>
                                          labels:
                                              org.opencontainers.image.created: <+pipeline.startTs>
                                              org.opencontainers.image.authors: luke.hertert@harness.io
                                              org.opencontainers.image.url: https://hub.docker.com/repository/docker/ldhertert/harness-buildpacks
                                              org.opencontainers.image.documentation: https://github.com/luke-hertert/harness-buildpacks#readme
                                              org.opencontainers.image.source: https://github.com/luke-hertert/harness-buildpacks
                                              org.opencontainers.image.version: <+stage.variables.version>
                                              org.opencontainers.image.revision: <+codebase.commitSha>
                                              org.opencontainers.image.vendor: Harness
                                              org.opencontainers.image.licenses: Apache 2.0
                                              org.opencontainers.image.title: Harness Buildpack CI plugin
                                              org.opencontainers.image.description: A Harness CI plugin that uses cloud native buildpacks to build docker images.
                                              org.opencontainers.image.base.digest: todo
                                              org.opencontainers.image.base.name: index.docker.io/library/docker:dind
                                      when:
                                          stageStatus: Success
                                          condition: <+pipeline.name> == "frank">
                                      failureStrategies: []
                                - step:
                                      type: BuildAndPushDockerRegistry
                                      name: Publish to Github Container Registry
                                      identifier: ghcr
                                      spec:
                                          connectorRef: Github_Container_Registry_lukehertert_org
                                          repo: ghcr.io/luke-hertert/<+stage.variables.image>
                                          tags:
                                              - <+codebase.branch>-<+codebase.commitSha>
                                          labels:
                                              org.opencontainers.image.created: <+pipeline.startTs>
                                              org.opencontainers.image.authors: luke.hertert@harness.io
                                              org.opencontainers.image.url: https://github.com/luke-hertert/harness-buildpacks/pkgs/container/harness-buildpacks
                                              org.opencontainers.image.documentation: https://github.com/luke-hertert/harness-buildpacks#readme
                                              org.opencontainers.image.source: https://github.com/luke-hertert/harness-buildpacks
                                              org.opencontainers.image.version: <+stage.variables.version>
                                              org.opencontainers.image.revision: <+codebase.commitSha>
                                              org.opencontainers.image.vendor: Harness
                                              org.opencontainers.image.licenses: Apache 2.0
                                              org.opencontainers.image.title: Harness Buildpack CI plugin
                                              org.opencontainers.image.description: A Harness CI plugin that uses cloud native buildpacks to build docker images.
                                              org.opencontainers.image.base.digest: todo
                                              org.opencontainers.image.base.name: index.docker.io/library/docker:dind
                                      when:
                                          stageStatus: Success
                                          condition: <+pipeline.name> == "frank">
                                      failureStrategies: []
                          - step:
                                type: S3Upload
                                name: Upload SBOMs
                                identifier: uploadSBOM
                                spec:
                                    connectorRef: Harness_AWS
                                    region: us-east-1
                                    bucket: luke-artifacts
                                    sourcePath: /step-outputs/**/*.json
                                    target: <+pipeline.identifier>/<+pipeline.executionId>/<+stage.identifier>
                                failureStrategies: []
                                when:
                                    stageStatus: Success
                                    condition: <+pipeline.name> == "frank">
                  serviceDependencies:
                      - identifier: dind
                        name: dind
                        type: Service
                        description: Docker in docker
                        spec:
                            connectorRef: account.Luke_Dockerhub
                            image: docker:dind
                            privileged: true
                            entrypoint:
                                - dockerd-entrypoint.sh
                  sharedPaths:
                      - /var/run
                      - /outputs
                      - /tmp
              variables:
                  - name: container
                    type: String
                    value: docker
                  - name: image
                    type: String
                    value: ldhertert/harness-buildpacks
                  - name: version
                    type: String
                    value: 1.0.0
    storeType: REMOTE
