pipeline:
    name: Harness Buildpacks Plugin Build
    identifier: Harness_Buildpacks_Plugin_Build
    projectIdentifier: Plugins
    orgIdentifier: default
    tags: {}
    properties:
        ci:
            codebase:
                connectorRef: lukehertert_GitHub_Org
                repoName: harness-buildpacks
                build:
                    type: branch
                    spec:
                        branch: main
    stages:
        - stage:
              name: Build
              identifier: Build
              type: CI
              spec:
                  cloneCodebase: true
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: laptopk8s
                          namespace: default
                          automountServiceAccountToken: true
                          nodeSelector: {}
                          os: Linux
                  execution:
                      steps:
                          - parallel:
                                - step:
                                      type: BuildAndPushDockerRegistry
                                      name: Publish to DockerHub
                                      identifier: Publish_to_DockerHub
                                      spec:
                                          connectorRef: account.Luke_Dockerhub
                                          repo: ldhertert/<+stage.variables.image>
                                          tags:
                                              - <+codebase.branch>-<+codebase.commitSha>
                                - step:
                                      type: BuildAndPushDockerRegistry
                                      name: Publish to Github Container Registry
                                      identifier: Publish_to_Github_Container_Registry
                                      spec:
                                          connectorRef: Github_Container_Registry_lukehertert_org
                                          repo: ghcr.io/luke-hertert/<+stage.variables.image>
                                          tags:
                                              - <+codebase.branch>-<+codebase.commitSha>
              variables:
                  - name: container
                    type: String
                    value: docker
                  - name: image
                    type: String
                    value: harness-buildpacks
