pipeline:
    name: harness-buildpacks
    identifier: Harness_Buildpacks_Plugin_Build
    projectIdentifier: Plugins
    orgIdentifier: default
    tags: {}
    properties:
        ci:
            codebase:
                connectorRef: lukehertert_GitHub_Org
                repoName: harness-buildpacks
                build: <+input>
    stages:
        - stage:
              name: Build
              identifier: Build
              type: CI
              spec:
                  cloneCodebase: true
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: laptopk8s
                          namespace: default
                          automountServiceAccountToken: true
                          nodeSelector: {}
                          os: Linux
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: dfdsd
                                identifier: dfdsd
                                spec:
                                    connectorRef: Luke_Dockerhub
                                    image: alpine
                                    shell: Sh
                                    command: echo "hi"
                  sharedPaths:
                      - /var/run
                      - /outputs
                      - /tmp
              variables:
                  - name: container
                    type: String
                    value: docker
                  - name: image
                    type: String
                    value: ldhertert/harness-buildpacks
                  - name: version
                    type: String
                    value: 1.0.0
                  - name: tags
                    type: String
                    value: <+codebase.branch>-<+pipeline.sequenceId>
    storeType: REMOTE
