pipeline:
    name: harness-buildpacks
    identifier: Harness_Buildpacks_Plugin_Build
    projectIdentifier: Plugins
    orgIdentifier: default
    tags: {}
    properties:
        ci:
            codebase:
                connectorRef: lukehertert_GitHub_Org
                repoName: harness-buildpacks
                build:
                    type: branch
                    spec:
                        branch: main
    stages:
        - stage:
              name: Build
              identifier: Build
              type: CI
              spec:
                  cloneCodebase: true
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: laptopk8s
                          namespace: default
                          automountServiceAccountToken: true
                          nodeSelector: {}
                          os: Linux
                  execution:
                      steps:
                          - step:
                                spec:
                                    connectorRef: account.Luke_Dockerhub
                                    image: plugins/docker
                                    privileged: true
                                    settings:
                                        dockerfile: Dockerfile
                                        pull_image: false
                                        daemon_off: "true"
                                        launch_debug: false
                                        squash: false
                                        bip: false
                                        tags: <+codebase.branch>-<+pipeline.sequenceId>
                                        username: ldhertert
                                        force_tag: false
                                        purge: false
                                        experimental: "true"
                                        repo: <+stage.variables.image>
                                        debug: false
                                        password: <+secrets.getValue("account.Luke_Dockerhub_Password")>
                                        insecure: false
                                        auto_tag: "false"
                                        compress: false
                                        dry_run: "true"
                                type: Plugin
                                name: Docker Build
                                identifier: Docker_Build
                                failureStrategies: []
                          - step:
                                name: Generate SBOM
                                identifier: Generate_SBOM
                                template:
                                    templateRef: Generate_SBOM
                                    versionLabel: v1
                                    templateInputs:
                                        type: Run
                                        spec:
                                            envVariables:
                                                image: <+stage.variables.image>
                                                tag: <+codebase.branch>-<+pipeline.sequenceId>
                                                outputDir: /outputs
                          - step:
                                type: S3Upload
                                name: Upload SBOMs
                                identifier: uploadSBOM
                                spec:
                                    connectorRef: Harness_AWS
                                    region: us-east-1
                                    bucket: luke-artifacts
                                    sourcePath: /outputs/**/*.json
                                    target: <+pipeline.identifier>/<+pipeline.executionId>/<+stage.identifier>
                          - step:
                                spec:
                                    connectorRef: account.Luke_Dockerhub
                                    image: plugins/docker
                                    privileged: true
                                    settings:
                                        dockerfile: Dockerfile
                                        pull_image: false
                                        daemon_off: "true"
                                        launch_debug: false
                                        squash: false
                                        bip: false
                                        tags: <+codebase.branch>-<+pipeline.sequenceId>
                                        username: ldhertert
                                        force_tag: false
                                        purge: false
                                        experimental: "true"
                                        repo: <+stage.variables.image>
                                        debug: false
                                        password: <+secrets.getValue("account.Luke_Dockerhub_Password")>
                                        insecure: false
                                        auto_tag: "false"
                                        compress: false
                                        dry_run: "false"
                                type: Plugin
                                name: Docker Push
                                identifier: docker_push
                                failureStrategies: []
                  serviceDependencies:
                      - identifier: dind
                        name: dind
                        type: Service
                        description: Docker in docker
                        spec:
                            connectorRef: account.Luke_Dockerhub
                            image: docker:dind
                            privileged: true
                            entrypoint:
                                - dockerd-entrypoint.sh
                  sharedPaths:
                      - /var/run
                      - /outputs
                      - /tmp
              variables:
                  - name: container
                    type: String
                    value: docker
                  - name: image
                    type: String
                    value: ldhertert/harness-buildpacks
                  - name: version
                    type: String
                    value: 1.0.0
    storeType: REMOTE
